from django.db import models

# Create your models here.

class Matches(models.Model):
    id = models.IntegerField(default=-1,primary_key=True)
    season = models.IntegerField(max_length=10,null=True)
    city = models.CharField(max_length=50,null=True)
    date = models.DateField(null=True, blank=True)
    team_1 = models.CharField(max_length=128)
    team_2 = models.CharField(max_length=64)
    toss_winner = models.CharField(max_length=64)
    toss_decision = models.CharField(max_length=64)
    result = models.CharField(max_length=64)
    dl_applied = models.BooleanField(default=False)
    winner = models.CharField(max_length=64,null=True)
    win_by_runs = models.IntegerField()
    win_by_wickets = models.IntegerField()
    player_of_match = models.CharField(max_length=64,null=True)
    venue = models.CharField(max_length=64,null=True)
    umpire1 = models.CharField(max_length=64,null=True)
    umpire2 = models.CharField(max_length=64,null=True)
    umpire3 = models.CharField(max_length=64,null=True)

class Deliveries(models.Model):
    match = models.ForeignKey(Matches, on_delete=models.CASCADE)
    inning = models.IntegerField(max_length=10)
    batting_team = models.CharField(max_length=50,null=True)
    bowling_team = models.CharField(max_length=50,null=True)
    over = models.IntegerField()
    ball = models.IntegerField()
    batsman = models.CharField(max_length=64,null=True)
    non_striker = models.CharField(max_length=64,null=True)
    bowler = models.CharField(max_length=64,null=True)
    is_super_over = models.BooleanField(default=False)
    wide_runs = models.IntegerField()
    bye_runs = models.IntegerField(max_length=64)
    legbye_runs = models.IntegerField()
    noball_runs = models.IntegerField()
    penalty_runs = models.IntegerField()
    batsman_runs = models.IntegerField()
    extra_runs = models.IntegerField()
    total_runs = models.IntegerField()
    player_dismissed = models.CharField(max_length=64,null=True)
    dismissal_kind = models.CharField(max_length=64,null=True)
    fielder = models.CharField(max_length=64,null=True)