# Generated by Django 2.2.2 on 2019-06-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('team_1', models.CharField(max_length=128)),
                ('team_2', models.CharField(max_length=64)),
                ('toss_winner', models.CharField(max_length=64)),
                ('toss_decision', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=64, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=64, null=True)),
                ('venue', models.CharField(max_length=64, null=True)),
                ('umpire1', models.CharField(max_length=64, null=True)),
                ('umpire2', models.CharField(max_length=64, null=True)),
                ('umpire3', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(max_length=10)),
                ('batting_team', models.CharField(max_length=50)),
                ('bowling_team', models.CharField(max_length=50)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=64)),
                ('non_striker', models.CharField(max_length=64)),
                ('bowler', models.CharField(max_length=64)),
                ('is_superover', models.BooleanField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField(max_length=64)),
                ('leg_bye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=64)),
                ('dismissal_kind', models.CharField(max_length=64)),
                ('fielder', models.CharField(max_length=64)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplapp.Matches')),
            ],
        ),
    ]
