# Generated by Django 2.2.2 on 2019-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='dl_applied',
            field=models.BooleanField(default=False),
        ),
    ]
