# Generated by Django 2.2.2 on 2019-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_auto_20190617_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='season',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
