# Generated by Django 2.2.2 on 2019-06-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0005_auto_20190617_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_id',
            field=models.IntegerField(default=-1),
        ),
    ]
